### ISSUE TITLE
Difficulties with install instructions

### ISSUE THREAD

**Issue by cosmicdreams** [elmsln/wcfactory#113]
When I try to follow the install instructions for wcfactory I run into errors such as: 
``` 
cweber-osx:project cweber$ env DEBUG=\* wcf start
  @oclif/config reading core plugin /Users/cweber/.config/yarn/global/node_modules/@wcfactory/cli +0ms
  @oclif/config loadJSON /Users/cweber/.config/yarn/global/node_modules/@wcfactory/cli/package.json +0ms
  @oclif/config loadJSON /Users/cweber/.config/yarn/global/node_modules/@wcfactory/cli/oclif.manifest.json +2ms
  @oclif/config:@wcfactory/cli using manifest from /Users/cweber/.config/yarn/global/node_modules/@wcfactory/cli/oclif.manifest.json +0ms
  @oclif/config reading user plugins pjson /Users/cweber/.local/share/@wcfactory/cli/package.json +0ms
  @oclif/config loadJSON /Users/cweber/.local/share/@wcfactory/cli/package.json +2ms
  @oclif/config loading plugins [ '@oclif/plugin-help' ] +1ms
  @oclif/config loadJSON /Users/cweber/.config/yarn/global/node_modules/@wcfactory/cli/package.json +3ms
  @oclif/config loadJSON /Users/cweber/.config/yarn/global/node_modules/@wcfactory/package.json +0ms
  @oclif/config loadJSON /Users/cweber/.config/yarn/global/node_modules/package.json +0ms
  @oclif/config reading core plugin /Users/cweber/.config/yarn/global/node_modules/@oclif/plugin-help +0ms
  @oclif/config loadJSON /Users/cweber/.config/yarn/global/node_modules/@oclif/plugin-help/package.json +0ms
  @oclif/config loadJSON /Users/cweber/.config/yarn/global/node_modules/@oclif/plugin-help/oclif.manifest.json +1ms
  @oclif/config:@oclif/plugin-help using manifest from /Users/cweber/.config/yarn/global/node_modules/@oclif/plugin-help/oclif.manifest.json +0ms
  @oclif/config config done +4ms
  @oclif/config start init hook +4ms
  @oclif/config init hook done +0ms
  wcf init version: @oclif/command@1.5.2 argv: [ 'start' ] +0ms
  @oclif/config runCommand start [] +5ms
  @oclif/config loadJSONSync /Users/cweber/.config/yarn/global/node_modules/@wcfactory/cli/tsconfig.json +10ms
  @oclif/config loadJSONSync /Users/cweber/.config/yarn/global/node_modules/@wcfactory/cli/tsconfig.json +1ms
Error: Cannot find module '/Users/cweber/.config/yarn/global/node_modules/@wcfactory/cli/lib/commands/start'
    at fetch (~/.config/yarn/global/node_modules/@oclif/config/lib/plugin.js:96:31)
    at Plugin.findCommand (~/.config/yarn/global/node_modules/@oclif/config/lib/plugin.js:114:21)
    at Object.load (~/.config/yarn/global/node_modules/@oclif/config/lib/plugin.js:47:72)
    at Config.runCommand (~/.config/yarn/global/node_modules/@oclif/config/lib/config.js:149:27)
    at Main.run (~/.config/yarn/global/node_modules/@oclif/command/lib/main.js:21:27)
    at Main._run (~/.config/yarn/global/node_modules/@oclif/command/lib/command.js:29:31)
    at <anonymous>
```

**Comment by btopro** [comment]
#109 related I think

**Comment by btopro** [comment]
@heyMP I was able to replicate part of this (tho it still worked)

It appears currently you have to have a company / user profile config or else it wont let u access the element and build commands. Must be related to their command scripts requiring that directory and it not existing until AFTER you establish a company

**Comment by cosmicdreams** [comment]
So.... update to the latest and I should be good?

**Comment by btopro** [comment]
I believe @heyMP changes are not in a point release yet

**Comment by btopro** [comment]
pushed up 0.3.2 now, let me know if that fixes it

**Comment by btopro** [comment]
🤕

**Comment by btopro** [comment]
@cosmicdreams some directories were missing in the publish vs git bc of the way npm works in reading package.json. I've fixed this in 0.4.0 can you give it a go again via `yarn global add @wcfactory/cli`

**Comment by cosmicdreams** [comment]
Much better, but there are still problems:

I can now run wcf start, but wcf factory generates this error:

```
identical themes/.gitkeep
events.js:167
      throw er; // Unhandled 'error' event
      ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:137:11)
    at Object.rename (fs.js:571:14)
    at module.exports.install (/Users/cweber/.config/yarn/global/node_modules/@wcfactory/generator-wcfactory/generators/factory/index.js:54:8)
    at Object.<anonymous> (/Users/cweber/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:424:27)
    at /Users/cweber/.config/yarn/global/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /Users/cweber/.config/yarn/global/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/Users/cweber/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:425:13)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
Emitted 'error' event at:
    at Immediate.setImmediate (/Users/cweber/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:433:22)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
cweber-osx:nerdery cweber$ 
```

**Comment by heyMP** [comment]
This is a depreciation issue with node 10.  It seems to work in node 8.

relates to #148

**Comment by cosmicdreams** [comment]
please don't close until I get all the way through without errors

**Comment by btopro** [comment]
148 is the hold up but Chris is right that way we track more possible future ones

**Comment by btopro** [comment]
@cosmicdreams give `yarn global add @wcfactory/cli` another shot to get 0.4.1 and then issue the `wcf factory` call again to see if it's fixed plz

**Comment by cosmicdreams** [comment]
Much further.  I was able to get the instruction: 
```
$ cd factories/factory-name
# create a new element
yarn run new
```

First, that's not where the runnable directory is.  The folder was more like: factories/git-organization/factory-name/

Second ```yarn run new``` didn't work because the package.json had illegal characters in it.

**Comment by cosmicdreams** [comment]
Looks like it's the generator that creates the illegal characters:

```
Initialized empty Git repository in /Users/cweber/OpenSource/nerdery/factories/wcf-factory/.git/


I'm all done. Running yarn install for you to install the required dependencies. If this fails, try running the command yourself.


yarn install v1.10.1
error package.json: Name contains illegal characters
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
yarn run v1.10.1
error package.json: Name contains illegal characters
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.10.1
error package.json: Name contains illegal characters
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[master (root-commit) 30bdd39] "Initial commit after wcfactory init"
```

**Comment by btopro** [comment]
Wcf element has replaced yarn run new

**Comment by btopro** [comment]
Christian that makes a lot of sense to me

**Comment by cosmicdreams** [comment]
Maybe I should blow away what was generated and try again....again.  Because running yarn start on the produced work still trips the ```package.json: Name contains illegal characters``` error.

**Comment by cosmicdreams** [comment]
Oh probably in the project name.  I have ```"name": "cosmicdreams/wcf-factory",```

**Comment by ChristianMurphy** [comment]
Aha, looks like it is missing the `@` at the start.

```
> const isValidNpmName = require('is-valid-npm-name');
> isValidNpmName('cosmicdreams/wcf-factory')
'package name had non-URL-safe characters, try using "cosmicdreams-wcf-factory" instead'
> isValidNpmName('@cosmicdreams/wcf-factory')
true
```

**Comment by cosmicdreams** [comment]
It should be noted that everywhere where the organization name is used should include an '@'.  After manually fixing the package name I'm able to discover other places causing errors as well.

**Comment by cosmicdreams** [comment]
After that, I think we'll have to talk about this error:  Missing dependency?

```
cweber-osx:wcf-factory cweber$ yarn start
yarn run v1.10.1
$ yarn run storybook
$ start-storybook -c .storybook -p 9001 -s ./elements
info @storybook/polymer v4.0.4
info 
info => Loading static files from: /Users/cweber/OpenSource/nerdery/factories/wcf-factory/elements .
info => Loading presets
ERR! Error: Cannot find module 'babel-loader/package.json' from '/Users/cweber/OpenSource/nerdery/factories/wcf-factory'
ERR!     at module.exports (/Users/cweber/OpenSource/nerdery/factories/wcf-factory/node_modules/resolve/lib/sync.js:43:15)
ERR!     at isBabelLoader8 (/Users/cweber/OpenSource/nerdery/factories/wcf-factory/node_modules/@storybook/core/dist/server/loadCustomBabelConfig.js:68:52)
ERR!     at _default (/Users/cweber/OpenSource/nerdery/factories/wcf-factory/node_modules/@storybook/core/dist/server/loadCustomBabelConfig.js:88:10)
ERR!     at Object.babel (/Users/cweber/OpenSource/nerdery/factories/wcf-factory/node_modules/@storybook/core/dist/server/core-preset-dev.js:36:45)
ERR!     at accumulationPromise.then.newConfig (/Users/cweber/OpenSource/nerdery/factories/wcf-factory/node_modules/@storybook/core/dist/server/presets.js:73:72)
ERR!     at process._tickCallback (internal/process/next_tick.js:68:7)
ERR!  { Error: Cannot find module 'babel-loader/package.json' from '/Users/cweber/OpenSource/nerdery/factories/wcf-factory'
ERR!     at module.exports (/Users/cweber/OpenSource/nerdery/factories/wcf-factory/node_modules/resolve/lib/sync.js:43:15)
ERR!     at isBabelLoader8 (/Users/cweber/OpenSource/nerdery/factories/wcf-factory/node_modules/@storybook/core/dist/server/loadCustomBabelConfig.js:68:52)
ERR!     at _default (/Users/cweber/OpenSource/nerdery/factories/wcf-factory/node_modules/@storybook/core/dist/server/loadCustomBabelConfig.js:88:10)
ERR!     at Object.babel (/Users/cweber/OpenSource/nerdery/factories/wcf-factory/node_modules/@storybook/core/dist/server/core-preset-dev.js:36:45)
ERR!     at accumulationPromise.then.newConfig (/Users/cweber/OpenSource/nerdery/factories/wcf-factory/node_modules/@storybook/core/dist/server/presets.js:73:72)
ERR!     at process._tickCallback (internal/process/next_tick.js:68:7)
ERR!   stack:
ERR!    'Error: Cannot find module \'babel-loader/package.json\' from \'/Users/cweber/OpenSource/nerdery/factories/wcf-factory\'\n    at module.exports (/Users/cweber/OpenSource/nerdery/factories/wcf-factory/node_modules/resolve/lib/sync.js:43:15)\n    at isBabelLoader8 (/Users/cweber/OpenSource/nerdery/factories/wcf-factory/node_modules/@storybook/core/dist/server/loadCustomBabelConfig.js:68:52)\n    at _default (/Users/cweber/OpenSource/nerdery/factories/wcf-factory/node_modules/@storybook/core/dist/server/loadCustomBabelConfig.js:88:10)\n    at Object.babel (/Users/cweber/OpenSource/nerdery/factories/wcf-factory/node_modules/@storybook/core/dist/server/core-preset-dev.js:36:45)\n    at accumulationPromise.then.newConfig (/Users/cweber/OpenSource/nerdery/factories/wcf-factory/node_modules/@storybook/core/dist/server/presets.js:73:72)\n    at process._tickCallback (internal/process/next_tick.js:68:7)',
ERR!   code: 'MODULE_NOT_FOUND' }
✨  Done in 4.85s.
cweber-osx:wcf-factory cweber$ 
```

**Comment by btopro** [comment]
that doesn't currently work. `yarn start` executed in the element created works. See if you can start working on that new element you made. storybook was having issues in 3.x and they just upgraded to 4.x which we've got in the installer but haven't wired up yet.

**Comment by cosmicdreams** [comment]
@ChristianMurphy after generating an element named 'hello-world'  the name: in the element's package.json was 'cosmicdreams/hello-world' instead of '@cosmicdreams/hello-world'

**Comment by btopro** [comment]
a PR to the docs to remove it and to ensure that @ detail is in there would be welcome so we can close this issue out and split it out into other things like #69 and any else

**Comment by cosmicdreams** [comment]
I have a solution for you in https://github.com/elmsln/wcfactory/issues/161

**Comment by btopro** [comment]
Committed the PR, let's close this now that it seems install is working. Documentation and what not found from here can be further cleaned up as you come across it. Thanks chris!
