### ISSUE TITLE
Error in oclif after install 

### ISSUE THREAD

**Issue by kat-wehr** [elmsln/wcfactory#144]
A4-DLRN-AM1306:~ kmw5340$ wcf start
Error: Cannot find module '/Users/kmw5340a/.config/yarn/global/node_modules/@wcfactory/cli/src/commands/start'
    at fetch (~a/.config/yarn/global/node_modules/@oclif/config/lib/plugin.js:96:31)
    at Plugin.findCommand (~a/.config/yarn/global/node_modules/@oclif/config/lib/plugin.js:114:21)
    at Object.load (~a/.config/yarn/global/node_modules/@oclif/config/lib/plugin.js:47:72)
    at Config.runCommand (~a/.config/yarn/global/node_modules/@oclif/config/lib/config.js:149:27)
    at Main.run (~a/.config/yarn/global/node_modules/@oclif/command/lib/main.js:21:27)
    at Main._run (~a/.config/yarn/global/node_modules/@oclif/command/lib/command.js:29:31)
A4-DLRN-AM1306:~ kmw5340$

**Comment by btopro** [comment]
`/Users/kmw5340a/.config/yarn/global/node_modules/@wcfactory/cli/src` does not exist for whatever reason...

**Comment by btopro** [comment]
@kat-wehr try running `yarn global add @wcfactory/cli` again. it should get new copies of something I just fixed.

**Comment by btopro** [comment]
yeah that fixes it!!!
