### ISSUE TITLE
.wcflibcache.json missing

### ISSUE THREAD

**Issue by starryeyez024** [elmsln/wcfactory#33]
@btopro Thanks for the readme updates! I ran through the instructions, and additionally I updated my versions of npm (6.4.1) and node (8.12.0)

When I run wcfactory new I get:
```
$ wcfactory new
fs.js:652
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/ktotten/Sites/kendalltotten/.wcflibcache.json'
    at Object.fs.openSync (fs.js:652:18)
    at Object.fs.readFileSync (fs.js:553:33)
    at Object.<anonymous> (/Users/ktotten/.config/yarn/global/node_modules/@wcfactory/generator-wcfactory/generators/app/index.js:11:41)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)

```

Here's a snapshot of the new directory I created via `wcfactory init`:
https://www.evernote.com/l/AA4lJM0tuVdBhaPyrnK3Z3G82g1Luyu99uQ

**Comment by btopro** [comment]
is this mac or PC? Also ensure yarn is up to date (no idea if that would have any implication for this) and `yarn global add @wcfactory/cli` again. earlier versions of the package threw the error you mentioned (earlier = yesterday)

**Comment by starryeyez024** [comment]
I installed Yarn with home brew yesterday for this purpose, so it should be up to date? This is on a MacBook, lastest OS. I can do a screen share if that helps.

**Comment by btopro** [comment]
fixed; was a node version issue
