### ISSUE TITLE
Start errors on "TypeError: Path must be a string. Received undefined"

### ISSUE THREAD

**Issue by ChristianMurphy** [elmsln/WCFactory#335]
Possibly related to `(node:5310) TypeError Plugin: @wcfactory/cli: Cannot read property 'companyDir' of undefined module: @oclif/config@1.10.4` not sure yet.
See full trace below.

```
$ wcf start --author test --copyrightOwner test --license MIT
/home/travis/.wcfconfig/ is missing! Run wcf start from your desired directory to get started!
/home/travis/.wcfconfig/ is missing! Run wcf start from your desired directory to get started!
/home/travis/.wcfconfig/ is missing! Run wcf start from your desired directory to get started!
/home/travis/.wcfconfig/ is missing! Run wcf start from your desired directory to get started!
(node:5310) TypeError Plugin: @wcfactory/cli: Cannot read property 'companyDir' of undefined
module: @oclif/config@1.10.4
task: toCached
plugin: @wcfactory/cli
root: /home/travis/build/elmsln/wcfactory/packages/cli
See more details with DEBUG=*
(node:5310) TypeError Plugin: @wcfactory/cli: Cannot read property 'companyDir' of undefined
module: @oclif/config@1.10.4
task: toCached
plugin: @wcfactory/cli
root: /home/travis/build/elmsln/wcfactory/packages/cli
See more details with DEBUG=*
Author name for your elements: test
Copyright owner of your work: test
Software License to use: MIT
events.js:183
      throw er; // Unhandled 'error' event
      ^
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:1233:7)
    at getPath (/home/travis/build/elmsln/wcfactory/node_modules/dir-glob/index.js:6:41)
    at globs.concat.map.x (/home/travis/build/elmsln/wcfactory/node_modules/dir-glob/index.js:47:59)
    at Array.map (<anonymous>)
    at module.exports.sync (/home/travis/build/elmsln/wcfactory/node_modules/dir-glob/index.js:47:33)
    at globDirs (/home/travis/build/elmsln/wcfactory/node_modules/globby/index.js:58:9)
    at getPattern (/home/travis/build/elmsln/wcfactory/node_modules/globby/index.js:61:64)
    at globTasks.reduce (/home/travis/build/elmsln/wcfactory/node_modules/globby/index.js:107:19)
    at Array.reduce (<anonymous>)
The command "wcf start --author test --copyrightOwner test --license MIT" exited with 1.
```

https://travis-ci.com/elmsln/wcfactory/jobs/169025745#L531-L566

**Comment by btopro** [comment]
the start command actually generates that property so we probably just need a trap somewhere of "this is currently making the thing" sorta logic

**Comment by ChristianMurphy** [comment]
This appears to have been resolved in latest https://travis-ci.com/elmsln/WCFactory/builds/106942166
