### ISSUE TITLE
throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by FDiskas** [elmsln/wcfactory#460]
```bash
$ wcf element
? Custom element base class to use SkateJS + lit-html -- data binding ++, very small library. 3 dependencies
? Element name demo-element
? Description / purpose of the element 
? Do you want to use Sass in this element? Yes
? Do want to use existing Sass dependencies? No thanks. I'll provide my own later
? Do you want custom properties? (typically yes) Yes
? Auto build support for the HAX authoring system? No
? Add a new property? (Y/n) 
? Add a new property? Yes
? Name (eg: title) title
? Name (eg: title) title
? type of value (the way it is used as data) (Use arrow keys)
? type of value (the way it is used as data) String, text based input
? Default value (leave blank for none) my title
? Default value (leave blank for none) my title
? Make available in css styles? [name="stuff"] { color: blue; } (y/N) y
? Make available in css styles? [name="stuff"] { color: blue; } Yes
? Observe changes to this property? (Y/n) 
? Observe changes to this property? Yes
? Add a new property? (Y/n) n
? Add a new property? No
events.js:167
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'pkg' of null
    at module.exports.writing (/home/***/.nvm/versions/node/v10.13.0/lib/node_modules/@wcfactory/cli/node_modules/@wcfactory/generator-wcfactory/generators/element/index.js:227:73)
    at Object.<anonymous> (/home/***/.nvm/versions/node/v10.13.0/lib/node_modules/@wcfactory/cli/node_modules/yeoman-generator/lib/index.js:424:27)
    at /home/***/.nvm/versions/node/v10.13.0/lib/node_modules/@wcfactory/cli/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /home/***/.nvm/versions/node/v10.13.0/lib/node_modules/@wcfactory/cli/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/home/***/.nvm/versions/node/v10.13.0/lib/node_modules/@wcfactory/cli/node_modules/yeoman-generator/lib/index.js:425:13)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
Emitted 'error' event at:
    at Immediate.setImmediate (/home/***/.nvm/versions/node/v10.13.0/lib/node_modules/@wcfactory/cli/node_modules/yeoman-generator/lib/index.js:433:22)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

**Comment by ChristianMurphy** [comment]
@FDiskas what is the `wcf --version`?

**Comment by FDiskas** [comment]
@wcfactory/cli/0.7.0 linux-x64 node-v10.13.0 :ballot_box_with_check:

**Comment by btopro** [comment]
commit should fix it; if there's no sass package defined (which the tooling stamps down a boilerplate one) then it could cause this error

**Comment by btopro** [comment]
0.7.1 published which should solve this
