### ISSUE TITLE
Error with build command

### ISSUE THREAD

**Issue by jedgar1mx** [elmsln/WCFactory#492]
I get this error with i ran `wcf build`
```events.js:167
      throw er; // Unhandled 'error' event
      ^

AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: /Users/doit/Documents/REPOS/detroitmi-components/templates/builds/_common/manifest.json
    at EditionInterface.exports.copy (/Users/doit/.config/yarn/global/node_modules/mem-fs-editor/lib/actions/copy.js:48:3)
    at EditionInterface.module.exports [as copyTpl] (/Users/doit/.config/yarn/global/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:29:8)
    at module.exports.writing (/Users/doit/.config/yarn/global/node_modules/@wcfactory/generator-wcfactory/generators/build/index.js:140:13)
    at Object.<anonymous> (/Users/doit/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:424:27)
    at /Users/doit/.config/yarn/global/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /Users/doit/.config/yarn/global/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/Users/doit/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:425:13)
    at runCallback (timers.js:693:18)
    at tryOnImmediate (timers.js:664:5)
Emitted 'error' event at:
    at Immediate.setImmediate (/Users/doit/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:433:22)
    at runCallback (timers.js:693:18)
    at tryOnImmediate (timers.js:664:5)
    at processImmediate (timers.js:646:5)```

**Comment by ChristianMurphy** [comment]
@jedgar1mx what is your `wcf --version`?

**Comment by ChristianMurphy** [comment]
Also does `lerna run build` run without errors?

**Comment by btopro** [comment]
https://github.com/elmsln/WCFactory/tree/master/packages/generator-wcfactory/generators/start/templates/templates/builds/_common

**Comment by jedgar1mx** [comment]
new error yay!!

```SyntaxError: Unexpected token < in JSON at position 322
    at JSON.parse (<anonymous>)
    at collectPackageConfigs (~/.config/yarn/global/node_modules/@wcfactory/common/config.js:122:40)
    at getConfigs (~/.config/yarn/global/node_modules/@wcfactory/common/config.js:103:26)
    at config (~/.config/yarn/global/node_modules/@wcfactory/common/config.js:20:19)
    at Object.<anonymous> (~/.config/yarn/global/node_modules/@wcfactory/common/config.js:258:25)
```

**Comment by ChristianMurphy** [comment]
@jedgar1mx what command did this come from? could you include a couple more lines from before the start of the log you attached?

**Comment by jedgar1mx** [comment]
it was coming from `wcf build` but it was cause because there was no public release yet so i had to do a connection to my root `node_modules` dependencies and run `polymer build` on the specific build folder

**Comment by btopro** [comment]
added this to an faq section today -- https://wcfactory.js.org/faq

**Comment by btopro** [comment]
@ChristianMurphy We were holding a sprint to get ppl setup w/ the tooling so that's why the messages were coming in w/ different errors throughout :). I've updated the docs to show this option https://wcfactory.js.org/faq

**Comment by ChristianMurphy** [comment]
> We were holding a sprint to get ppl setup w/ the tooling so that's why the messages were coming in w/ different errors throughout

@btopro that explains a lot :slightly_smiling_face:
