### ISSUE TITLE
`wfc element` not working 

### ISSUE THREAD

**Issue by jedgar1mx** [elmsln/WCFactory#515]
I was trying to create a new element in my windows machine after pulling down my factory from git. I keep getting this error:
`TypeError: Cannot read property 'value' of undefined                                 at Object.when (C:/Users/montesje/AppData/Local/Yarn/Data/global/node_module s/@wcfactory/cli/src/questions/element.js:25:40)                                     at promptUser (C:/Users/montesje/AppData/Local/Yarn/Data/global/node_modules /@wcfactory/cli/src/utils/commands.js:34:40)                                         at Element.run (C:/Users/montesje/AppData/Local/Yarn/Data/global/node_module s/@wcfactory/cli/src/commands/element.js:12:19)                                      at Element._run (C:/Users/montesje/AppData/Local/Yarn/Data/global/node_modul es/@oclif/command/lib/command.js:35:31)`

**Comment by jedgar1mx** [comment]
Should the process be? 
1. Install `WCFactory`
2. Pull the factory from `git` into the `factories` folder.
3. Run `yarn install`

**Comment by ChristianMurphy** [comment]
This is element creation process being followed by CI.
https://github.com/elmsln/WCFactory/blob/a55d149c2e38fa382ec1b921f937b9ec7679299e/.travis.yml#L24-L28

`wcf start` and `wcf factory` should both be called before starting on individual elements.

**Comment by btopro** [comment]
Process should be to:
- install WCFactory
- run `wcfactory start` (because it needs the company housing to know where to run commands relative to).
- now you can git clone your factory into company/factories/your-factory-name-here

Also make sure that when you run wcf start that you install it in a directory above your user / home directory. This has helped in the past.

**Comment by jedgar1mx** [comment]
Still getting errors:
`AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist : C:\Users\montesje\AppData\Local\Yarn\Data\global\node_modules\@wcfactory\gener ator-wcfactory\generators\element\templates\licenses\undefined.md                    at EditionInterface.exports.copy (C:\Users\montesje\AppData\Local\Yarn\Data\ global\node_modules\mem-fs-editor\lib\actions\copy.js:48:3)                          at EditionInterface.module.exports [as copyTpl] (C:\Users\montesje\AppData\L ocal\Yarn\Data\global\node_modules\mem-fs-editor\lib\actions\copy-tpl.js:29:8)       at module.exports.writing (C:\Users\montesje\AppData\Local\Yarn\Data\global\ node_modules\@wcfactory\generator-wcfactory\generators\element\index.js:246:13)      at Object. (C:\Users\montesje\AppData\Local\Yarn\Data\global\node _modules\yeoman-generator\lib\index.js:424:27)                                       at C:\Users\montesje\AppData\Local\Yarn\Data\global\node_modules\run-async\i ndex.js:25:25                                                                        at new Promise ()                                                     at C:\Users\montesje\AppData\Local\Yarn\Data\global\node_modules\run-async\i ndex.js:24:19                                                                        at self.env.runLoop.add.completed (C:\Users\montesje\AppData\Local\Yarn\Data \global\node_modules\yeoman-generator\lib\index.js:425:13)                           at runCallback (timers.js:705:18)                                                at tryOnImmediate (timers.js:676:5)                                          Emitted 'error' event at:                                                            at Immediate.setImmediate (C:\Users\montesje\AppData\Local\Yarn\Data\global\ node_modules\yeoman-generator\lib\index.js:433:22)                                   at runCallback (timers.js:705:18)                                                at tryOnImmediate (timers.js:676:5)                                              at processImmediate (timers.js:658:5)
--
`

**Comment by btopro** [comment]
is it allowing you to pick a license? also seems like maybe the wcf start command doesnt have a license picked by default or something in this setup hence the initial "undefined.md "

**Comment by jedgar1mx** [comment]
No it doesn't let me pick a license
